const ID = 5
const USERNAME = 8
const PASSWORD = 4
const STATUS_CODE_SUCCESS = 200
const STATUS_CODE_FAIL = 400
const RANDOM_STRING_FOR_CONCAT = 5

module.exports = {
  ID,
  USERNAME,
  PASSWORD,
  STATUS_CODE_FAIL,
  STATUS_CODE_SUCCESS,
  RANDOM_STRING_FOR_CONCAT
}
